const musicdata=[
    {id:1,src:'./assetce/audios/MusicData/1/src/Charlie Puth - We Don\'t Talk Anymore ft. Selena Gomez.mp3',
    img:'./assetce/audios/MusicData/1/img/Charlie Puth - We Don\'t Talk Anymore ft. Selena Gomez.jpg',
    artiste:"Charlie Puth",
    track:'Don\'t Talk Anymore'},
    {id:2,src:'./assetce/audios/MusicData/2/src/Maroon 5 - One More Night.mp3',
    img:'./assetce/audios/MusicData/2/img/Maroon 5 - One More Night.png',
    artiste:"Maroon 5",
    track:'one more night'},
    {id:3,src:'./assetce/audios/MusicData/3/src/Paramore - decode.mp3',
    img:'./assetce/audios/MusicData/3/img/Paramore - decode.jpg',
    artiste:"paramore",
    track:'decode'},
    {id:4,src:'./assetce/audios/MusicData/4/src/Paramore _ That\'s What You Get.mp3',
    img:'./assetce/audios/MusicData/4/img/Paramore _ That\'s What You Get.jpg',
    artiste:"Paramore",
    track:'That\'s What You Get'},
    {id:5,src:'./assetce/audios/MusicData/5/src/The Kid LAROI - STAY ft. Justin Bieber.mp3',
    img:'./assetce/audios/MusicData/5/img/The Kid LAROI - STAY ft. Justin Bieber.jpg',
    artiste:"The Kid LAROI,Justin Bieber",
    track:'Stay'},
    {id:6,src:'./assetce/audios/MusicData/6/src/Paramore - Misery Business.mp3',
    img:'./assetce/audios/MusicData/6/img/Paramore - Misery Business.jpg',
    artiste:"Paramore",
    track:'Misery Business'},
    {id:7,src:'./assetce/audios/MusicData/7/src/will.i.am - thatPOWER ft. Justin Bieber.mp3',
    img:'./assetce/audios/MusicData/7/img/will.i.am - thatPOWER ft. Justin Bieber.jpg',
    artiste:"thatPOWER,Justin Bieber",
    track:'will.i.am'},
    {id:8,src:'./assetce/audios/MusicData/8/src/Maroon 5 - Maps.mp3',
    img:'./assetce/audios/MusicData/8/img/Maroon 5 - Maps.png',
    artiste:"Maroon 5",
    track:'Maps'},
    {id:9,src:'./assetce/audios/MusicData/9/src/OneRepublic - I Ain\'t Worried.mp3',
    img:'./assetce/audios/MusicData/9/img/OneRepublic - I Ain\'t Worried.jpg',
    artiste:"OneRepublic",
    track:'I Ain\'t Worried'},
    {id:10,src:'./assetce/audios/MusicData/10/src/Passenger - Let Her go.mp3',
    img:'./assetce/audios/MusicData/10/img/Passenger - Let Her go.jpg',
    artiste:"Passenger",
    track:'Let Her go'},
    {id:11,src:'./assetce/audios/MusicData/11/src/Post Malone - Goodbyes ft. Young Thug.mp3',
    img:'./assetce/audios/MusicData/11/img/Post Malone - Goodbyes ft. Young Thug.png',
    artiste:"Post Malone,Young Thug",
    track:'Goodbyes'},
    {id:12,src:'./assetce/audios/MusicData/12/src/Post Malone - White Iverson.mp3',
    img:'./assetce/audios/MusicData/12/img/Post Malone - White Iverson.jpg',
    artiste:"Post Malone",
    track:'White Iverson'},
    {id:13,src:'./assetce/audios/MusicData/13/src/Taylor Swift - Bad Blood.mp3',
    img:'./assetce/audios/MusicData/13/img/Taylor Swift - Bad Blood.png',
    artiste:"Taylor Swift",
    track:'Bad Blood'},
    {id:14,src:'./assetce/audios/MusicData/14/src/Tom Odell - I Know.mp3',
    img:'./assetce/audios/MusicData/14/img/Tom Odell - I Know.jpg',
    artiste:"Tom Odell",
    track:'I Know'}
  ]
export default musicdata